apiVersion: v1
kind: Service
metadata:
  name: nginx-www
  labels:
    app: nginx-www
spec:
  selector:
    app: nginx-www
  ports:
    - port: 80
      name: http
      targetPort: 80
  type: ClusterIP
